import React, { useState } from 'react';
import { PlusCircle, Sparkles, Video, FileText, Code2, Zap, Trophy, Megaphone, Radio, CheckCircle2, ArrowRight } from 'lucide-react';
import type { ReelItem } from '../../types/eduvia';

interface CreatorStudioProps {
  onPublishReel: (reel: ReelItem) => void;
}

export const CreatorStudio: React.FC<CreatorStudioProps> = ({ onPublishReel }) => {
  const [selectedType, setSelectedType] = useState<string>('Reel');
  const [videoScript, setVideoScript] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [generatedResult, setGeneratedResult] = useState<{
    title: string;
    description: string;
    topic: string;
    skills: string;
    quizCount: number;
    codeChallengeCreated: boolean;
  } | null>(null);

  const contentTypes = [
    { name: 'Reel', icon: Video, color: 'text-rose-400', label: '🎥 Reel' },
    { name: 'Post', icon: FileText, color: 'text-indigo-400', label: '📝 Post' },
    { name: 'Lesson', icon: Sparkles, color: 'text-cyan-400', label: '🧠 Lesson' },
    { name: 'Code', icon: Code2, color: 'text-emerald-400', label: '💻 Code' },
    { name: 'Challenge', icon: Zap, color: 'text-amber-400', label: '⚡ Challenge' },
    { name: 'Project', icon: Trophy, color: 'text-purple-400', label: '🏗️ Project' },
    { name: 'Opportunity', icon: Megaphone, color: 'text-blue-400', label: '📢 Opportunity' },
    { name: 'Live', icon: Radio, color: 'text-rose-500', label: '🔴 Live' }
  ];

  const handleAiAutoGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    if (!videoScript.trim()) return;

    setIsGenerating(true);

    setTimeout(() => {
      setIsGenerating(false);
      setGeneratedResult({
        title: videoScript.length > 30 ? videoScript.substring(0, 45) + '...' : 'Python Fast Execution Techniques',
        description: 'Auto-extracted transcript & concept breakdown by Eduvia AI Engine.',
        topic: 'Python',
        skills: 'Python • Advanced Algorithms',
        quizCount: 3,
        codeChallengeCreated: true
      });
    }, 1200);
  };

  const handlePublish = () => {
    if (!generatedResult) return;

    const newReel: ReelItem = {
      id: `reel-${Date.now()}`,
      title: generatedResult.title,
      description: generatedResult.description,
      videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-code-running-on-a-computer-screen-41566-large.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop',
      creator: {
        name: 'Shaik Sowban',
        handle: '@sowban_dev',
        avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop',
        title: 'CSM • Creator',
        verified: true
      },
      topic: generatedResult.topic,
      skillTag: generatedResult.skills,
      level: 'Intermediate',
      likes: 1,
      commentsCount: 0,
      saves: 0,
      shares: 0,
      understandBreakdown: {
        beginner: `Auto-generated summary: ${videoScript.substring(0, 80)}`,
        intermediate: 'Under the hood execution analysis generated by AI engine.',
        advanced: 'Performance optimization metrics for memory and execution velocity.',
        keyTakeaways: [
          'Evaluates bytecode speed inside CPython runtime',
          'Eliminates repetitive method lookup overhead',
          'Optimized for clean functional expression'
        ]
      },
      quiz: [
        {
          id: `q-${Date.now()}`,
          question: `What is the primary performance advantage of: "${generatedResult.title}"?`,
          options: [
            'CPython bytecode velocity without method lookup overhead',
            'Standard loop with repeated append calls',
            'Slower runtime execution'
          ],
          correctAnswer: 0,
          explanation: 'Evaluating expressions directly in C speed inside CPython provides optimal runtime performance.'
        }
      ]
    };

    onPublishReel(newReel);
    alert('🎉 Success! Your video has been transformed by EDUVIA AI into an interactive Reel with real quizzes & coding challenges and published to the feed!');
    setGeneratedResult(null);
    setVideoScript('');
  };

  return (
    <div className="w-full max-w-3xl mx-auto space-y-6 pb-24 animate-fadeIn">
      {/* Header */}
      <div className="glass-card p-6 border border-purple-500/30 bg-gradient-to-r from-purple-950/60 via-slate-950 to-indigo-950/60">
        <div className="flex items-center space-x-3">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-purple-500 to-indigo-500 flex items-center justify-center text-white font-bold shadow-lg shadow-purple-500/30">
            <PlusCircle className="w-7 h-7" />
          </div>
          <div>
            <h2 className="text-xl font-extrabold text-white flex items-center gap-2">
              EDUVIA AI Creator Studio
              <span className="text-xs font-normal text-purple-300 bg-purple-500/20 px-2 py-0.5 rounded-full border border-purple-500/30">
                1-Click Lesson Builder
              </span>
            </h2>
            <p className="text-xs text-slate-300">
              Upload 1 video or script — AI automatically builds captions, transcripts, quizzes, coding challenges, & skill tags!
            </p>
          </div>
        </div>
      </div>

      {/* 9. CONTENT TYPES SELECTOR GRID */}
      <div className="glass-card p-5 border border-white/10">
        <h3 className="text-xs font-extrabold text-slate-400 uppercase tracking-wider mb-3">
          Select Content Type
        </h3>
        <div className="grid grid-cols-4 sm:grid-cols-8 gap-2">
          {contentTypes.map((type) => {
            const Icon = type.icon;
            const isSel = selectedType === type.name;
            return (
              <button
                key={type.name}
                onClick={() => setSelectedType(type.name)}
                className={`p-3 rounded-2xl border flex flex-col items-center justify-center transition-all ${
                  isSel
                    ? 'bg-purple-600/30 border-purple-500 text-white shadow-lg shadow-purple-500/20 font-bold'
                    : 'bg-white/5 border-white/5 text-slate-400 hover:bg-white/10 hover:text-white'
                }`}
              >
                <Icon className={`w-5 h-5 mb-1 ${type.color}`} />
                <span className="text-[10px] font-semibold">{type.name}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* 10. AI CREATOR GENERATOR WORKFLOW */}
      <div className="glass-card p-6 border border-cyan-500/30 bg-black/40">
        <h3 className="text-sm font-extrabold text-white mb-2 flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-cyan-400" />
          Paste Video Script or Educational Text
        </h3>

        <form onSubmit={handleAiAutoGenerate} className="space-y-4">
          <textarea
            value={videoScript}
            onChange={(e) => setVideoScript(e.target.value)}
            placeholder="e.g. In this 60 second video, I explain how Python list comprehensions work using [x**2 for x in numbers if x % 2 == 0] to double performance..."
            className="w-full h-36 bg-black/60 border border-white/15 rounded-2xl p-4 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500 font-sans leading-relaxed"
          />

          <div className="flex items-center justify-between">
            <span className="text-[11px] text-slate-400">
              🤖 AI automatically constructs 3 quiz questions & live coding editor challenge.
            </span>

            <button
              type="submit"
              disabled={isGenerating || !videoScript.trim()}
              className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 via-indigo-500 to-purple-600 text-white font-bold text-xs flex items-center space-x-2 shadow-lg shadow-indigo-500/30 hover:scale-105 transition-all disabled:opacity-50"
            >
              <Sparkles className="w-4 h-4" />
              <span>{isGenerating ? 'AI Auto-Generating...' : 'Transform into Learning Experience'}</span>
            </button>
          </div>
        </form>
      </div>

      {/* AI GENERATED RESULT PREVIEW CARD */}
      {generatedResult && (
        <div className="glass-card p-6 border border-emerald-500/40 bg-emerald-950/20 space-y-4 animate-fadeIn">
          <div className="flex items-center space-x-2 text-emerald-400 text-xs font-bold uppercase tracking-wider">
            <CheckCircle2 className="w-4 h-4" />
            <span>AI Mini-Learning Experience Generated</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
            <div className="p-3 rounded-xl bg-black/40 border border-white/10">
              <span className="text-slate-400 block text-[10px]">Title</span>
              <span className="font-bold text-white">{generatedResult.title}</span>
            </div>
            <div className="p-3 rounded-xl bg-black/40 border border-white/10">
              <span className="text-slate-400 block text-[10px]">Auto Quizzes</span>
              <span className="font-bold text-amber-300">{generatedResult.quizCount} Questions Created</span>
            </div>
            <div className="p-3 rounded-xl bg-black/40 border border-white/10">
              <span className="text-slate-400 block text-[10px]">Coding Sandbox</span>
              <span className="font-bold text-cyan-300">Python Sandbox Ready</span>
            </div>
          </div>

          <button
            onClick={handlePublish}
            className="w-full py-3 rounded-2xl bg-gradient-to-r from-emerald-500 to-teal-600 text-white font-extrabold text-xs shadow-lg shadow-emerald-500/30 hover:scale-[1.01] transition-transform flex items-center justify-center space-x-2"
          >
            <span>Publish EduReel to Social Feed</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}
    </div>
  );
};
